### ISSUE TITLE
ACTUALIZACIÓN PARA VERSIÓN 16

### ISSUE THREAD

**Issue by erik21111111** [kamicase24/hr_ven_payroll#1]
Buenas tardes, una pregunta... De casualidad no tiene una actualización de este modulo para Odoo versión 16, o no sabrá si de casualidad este mismo modulo me sirve para calcular la cantidad de días lunes? gracias.

**Comment by jrojas-python** [comment]
Hola, lamentablemente no he actualizado este modulo para las nuevas versiones de Odoo, si quieres calcular los lunes de un mes puedes utilizar la libreria calendar de python.

**Comment by erik21111111** [comment]
Entiendo, Muchas gracias...
